repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [ --line-length=120 ]

  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v25.0.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          # - "--ignore=E203,E266,E501,W503,F403,F401,E402"